### ISSUE TITLE
Error message when launching in 1.19

### ISSUE THREAD

**Issue by kevin-smits** [LXYan2333/Fabric-Bedrock-Miner#44]
The game won't launch, with the following error code:

Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod bedrockminer
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:441)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:439)
	... 3 more

**Comment by kevin-smits** [comment]
Resolved after restarting twice
